### ISSUE TITLE
Zmiany do nowej wersji

### ISSUE THREAD

**Issue by Jager4561** [FrostyCoders/HaikuConnectsUs#19]
## Nowa wersja
0.1.1 - w przypadku naprawy drobnych bugów, które utrudniają działanie aplikacji
0.2.0 - w przypadku większych zmian (nowe funkcje, przerobione funkcje itp.)
###
**W komentarzach pisać wszystkie wprowadzone zmiany do change loga w dokumentacji**

**Comment by Jager4561** [comment]
1. Ujednolicenie nazw błędów i komunikatów

**Comment by nietutejszyy** [comment]
2. Zmiana nazwy strony
3. Zmiana wyglądu komunikatów na stronie

**Comment by Jager4561** [comment]
4. Naprawiono błędy odświeżania i edycji autorów.

**Comment by nietutejszyy** [comment]
5. Dodanie podstawowego seo
6. Ułożenie alfabetyczne właściwości w plikach css
7. Małe poprawki we frondendzie

**Comment by Jager4561** [comment]
8. Optymalizacja kodu Javascript
